---
mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '17.3'
    tailf-ned-cisco-ios:service:
      conf: {}
      timestamps: {}
      call-home:
      - null
    tailf-ned-cisco-ios:login:
      on-success: {}
    tailf-ned-cisco-ios:cdp:
      run: true
    tailf-ned-cisco-ios:platform:
      console: serial
      punt-keepalive:
        disable-kernel-core: true
      qfp:
        utilization:
          monitor:
            load: 80
    tailf-ned-cisco-ios:call-home:
      contact-email-addr: sch-smart-licensing@cisco.com
      profile:
      - name: CiscoTAC-1
        active: true
        reporting:
          smart-licensing-data: true
        destination:
          transport-method:
            http:
            - null
    tailf-ned-cisco-ios:ip:
      gratuitous-arps-conf: {}
      bootp:
        server: true
      domain:
        lookup-conf:
          lookup: true
      name-server: {}
      ssh:
        server:
          algorithm: {}
        client:
          algorithm:
            encryption:
            - aes128-ctr
            - aes192-ctr
            - aes256-ctr
      forward-protocol:
        nd:
        - null
      http: {}
      bgp-community:
        new-format:
        - null
      nat:
        inside:
          source:
            list-vrf:
              list:
              - id: nat-internal
                vrf: internal_1
                interface: GigabitEthernet8
                overload:
                - null
      access-list:
        standard: {}
    tailf-ned-cisco-ios:subscriber:
      templating: true
    tailf-ned-cisco-ios:multilink:
      bundle-name: authenticated
    tailf-ned-cisco-ios:username:
    - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      privilege: 15
      secret:
        type: '9'
        secret: $9$.LrFX9G/ubDpdU$uVni6LtpWdZ1oy6abP6a.mtacCSWPdCCnZWtqRzrMcE
    tailf-ned-cisco-ios:redundancy: {}
    tailf-ned-cisco-ios:crypto:
      pki:
        trustpoint:
        - id: SLA-TrustPoint
          enrollment:
            pkcs12:
            - null
          revocation-check:
          - crl
        - id: TP-self-signed-1865052687
          enrollment:
            selfsigned:
            - null
          subject-name: cn=IOS-Self-Signed-Certificate-1865052687
          revocation-check:
          - none
          rsakeypair:
            key-label: TP-self-signed-1865052687
        certificate:
          chain:
          - name: SLA-TrustPoint
            certificate:
            - serial: '01'
              cert-type: ca
              cert: "  30820321 30820209 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 0B050030 \r\n  32310E30 0C060355 040A1305 43697363 6F312030 1E060355\
                \ 04031317 43697363 \r\n  6F204C69 63656E73 696E6720 526F6F74 20434130\
                \ 1E170D31 33303533 30313934 \r\n  3834375A 170D3338 30353330 31393438\
                \ 34375A30 32310E30 0C060355 040A1305 \r\n  43697363 6F312030 1E060355\
                \ 04031317 43697363 6F204C69 63656E73 696E6720 \r\n  526F6F74 20434130\
                \ 82012230 0D06092A 864886F7 0D010101 05000382 010F0030 \r\n  82010A02\
                \ 82010100 A6BCBD96 131E05F7 145EA72C 2CD686E6 17222EA1 F1EFF64D \r\
                \n  CBB4C798 212AA147 C655D8D7 9471380D 8711441E 1AAF071A 9CAE6388\
                \ 8A38E520 \r\n  1C394D78 462EF239 C659F715 B98C0A59 5BBB5CBD 0CFEBEA3\
                \ 700A8BF7 D8F256EE \r\n  4AA4E80D DB6FD1C9 60B1FD18 FFC69C96 6FA68957\
                \ A2617DE7 104FDC5F EA2956AC \r\n  7390A3EB 2B5436AD C847A2C5 DAB553EB\
                \ 69A9A535 58E9F3E3 C0BD23CF 58BD7188 \r\n  68E69491 20F320E7 948E71D7\
                \ AE3BCC84 F10684C7 4BC8E00F 539BA42B 42C68BB7 \r\n  C7479096 B4CB2D62\
                \ EA2F505D C7B062A4 6811D95B E8250FC4 5D5D5FB8 8F27D191 \r\n  C55F0D76\
                \ 61F9A4CD 3D992327 A8BB03BD 4E6D7069 7CBADF8B DF5F4368 95135E44 \r\
                \n  DFC7C6CF 04DD7FD1 02030100 01A34230 40300E06 03551D0F 0101FF04\
                \ 04030201 \r\n  06300F06 03551D13 0101FF04 05300301 01FF301D 0603551D\
                \ 0E041604 1449DC85 \r\n  4B3D31E5 1B3E6A17 606AF333 3D3B4C73 E8300D06\
                \ 092A8648 86F70D01 010B0500 \r\n  03820101 00507F24 D3932A66 86025D9F\
                \ E838AE5C 6D4DF6B0 49631C78 240DA905 \r\n  604EDCDE FF4FED2B 77FC460E\
                \ CD636FDB DD44681E 3A5673AB 9093D3B1 6C9E3D8B \r\n  D98987BF E40CBD9E\
                \ 1AECA0C2 2189BB5C 8FA85686 CD98B646 5575B146 8DFC66A8 \r\n  467A3DF4\
                \ 4D565700 6ADF0F0D CF835015 3C04FF7C 21E878AC 11BA9CD2 55A9232C \r\
                \n  7CA7B7E6 C1AF74F6 152E99B7 B1FCF9BB E973DE7F 5BDDEB86 C71E3B49\
                \ 1765308B \r\n  5FB0DA06 B92AFE7F 494E8A9E 07B85737 F3A58BE1 1A48A229\
                \ C37C1E69 39F08678 \r\n  80DDCD16 D6BACECA EEBC7CF9 8428787B 35202CDC\
                \ 60E4616A B623CDBD 230E3AFB \r\n  418616A9 4093E049 4D10AB75 27E86F73\
                \ 932E35B5 8862FDAE 0275156F 719BB2F0 \r\n  D697DF7F 28\r\n"
          - name: TP-self-signed-1865052687
            certificate:
            - serial: '01'
              cert-type: self-signed
              cert: "  30820330 30820218 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 05050030 \r\n  31312F30 2D060355 04031326 494F532D 53656C66 2D536967\
                \ 6E65642D 43657274 \r\n  69666963 6174652D 31383635 30353236 3837301E\
                \ 170D3233 30353136 31363333 \r\n  35355A17 0D333330 35313531 36333335\
                \ 355A3031 312F302D 06035504 03132649 \r\n  4F532D53 656C662D 5369676E\
                \ 65642D43 65727469 66696361 74652D31 38363530 \r\n  35323638 37308201\
                \ 22300D06 092A8648 86F70D01 01010500 0382010F 00308201 \r\n  0A028201\
                \ 0100ACAB FED6D8C6 C3C441F7 4A27B86D F03FBFF6 062D4B6E 96355631 \r\
                \n  32699BBD A2CD155A 978E8B89 6EEF4FE3 85777A9A 51055F11 060D432D\
                \ 1206BEE0 \r\n  85EFF7CD F6E18F89 3CF874C3 7BD922DC 004F0F45 6CC4E5C8\
                \ 6263F6DE F26EA87A \r\n  14E7F683 DB238351 7F70D767 4F3069BC 4A5F26EF\
                \ 475E31F7 75303FE5 A08FFE75 \r\n  BD23B1F3 3C512129 9294FDCC 00C1A750\
                \ E762DAA5 8797E2E3 7DF90F68 F42DADD4 \r\n  5340583C 5335FAC6 BDB17C44\
                \ 8FEBCE3A 6F56B6C2 A47E9534 E4D67472 178F011F \r\n  8213DEF0 94118024\
                \ C2687CEF 7C2E32B8 653D5D9C 0AA487A0 B92E853D CA67E180 \r\n  B5634DAD\
                \ B37D656F 7E88F716 19978E17 7CE841DB 163FCDB3 331160D9 46777BF3 \r\
                \n  866A6DAB 49BD0203 010001A3 53305130 0F060355 1D130101 FF040530\
                \ 030101FF \r\n  301F0603 551D2304 18301680 14459A03 FDE3C47D B2EC049E\
                \ DC9176E9 0426B7B7 \r\n  71301D06 03551D0E 04160414 459A03FD E3C47DB2\
                \ EC049EDC 9176E904 26B7B771 \r\n  300D0609 2A864886 F70D0101 05050003\
                \ 82010100 532B1A4B CE2A7C78 FDEADB0C \r\n  10373A6E 7FFCD40B 32EB5472\
                \ 0EA86DEF 645014E3 77CADC8C 2F09C8C4 04A3DCE7 \r\n  BDC5F78A F020BEAF\
                \ 9EF6B455 90FABA56 F321008C 5B08E75A D404A2D7 8FDD227F \r\n  8A1797DE\
                \ F3D511BD 5568C98B 8BFA560A 919B6F58 30359592 05922433 0FD741ED \r\
                \n  A50BCF70 7D108A08 11CC8CD6 A9387B9D 462729ED E3FDB90C 42581B7C\
                \ 206F8F74 \r\n  89F62FA1 81D8770D EDF97871 25EF6592 46BB41DB BE652EDE\
                \ 67D9C0AF 9D66E194 \r\n  0224AF40 04C532FF 74855E57 20A56ED6 F23D01C5\
                \ 7C1957D3 A6DD2B2F D3F2FDA0 \r\n  E8FB3B58 1298A920 FDE8D0F6 B464CCAA\
                \ CCA495B7 EF9C798F EF67FA03 93818CED \r\n  905A7BDF AAE0C4DD BE5AE3C9\
                \ CED01FF2 628B8D59\r\n"
    tailf-ned-cisco-ios:interface:
      Loopback:
      - name: '0'
        vrf:
          forwarding: internal_1
        ip:
          address: {}
      GigabitEthernet:
      - name: '1'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        vrf:
          forwarding: Mgmt-intf
        ip:
          address:
            dhcp: {}
      - name: '2'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '2.10'
        vrf:
          forwarding: internal_1
        ip:
          address: {}
          nat: {}
      - name: '3'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '4'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '5'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '6'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '7'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '8'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        ip:
          address: {}
          nat: {}
    tailf-ned-cisco-ios:banner: {}
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
      - first: '0'
        stopbits: '1'
      vty:
      - first: 0
        last: 4
        login:
          local:
          - null
        transport:
          input:
          - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      monitor: {}
      facility: syslog
    tailf-ned-cisco-ios:ntp:
      server:
        peer-list:
        - name: 216.239.35.0
        - name: 216.239.35.4
    tailf-ned-cisco-ios:spanning-tree:
      extend:
        system-id:
        - null
    tailf-ned-cisco-ios:diagnostic:
      bootup:
        level: minimal
    tailf-ned-cisco-ios:router:
      bgp:
      - as-no: 100
        address-family:
          ipv4:
          - af: unicast
      ospf:
      - id: 1
        vrf: internal_1
        default-information:
          originate: {}
        network:
        - ip: 172.16.0.50
          mask: 0.0.0.0
          area: 0
        - ip: 172.16.255.5
          mask: 0.0.0.0
          area: 0
    tailf-ned-cisco-ios:memory:
      free:
        low-watermark:
          processor: 71489
