---
mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '17.3'
    tailf-ned-cisco-ios:service:
      conf: {}
      timestamps: {}
      call-home:
      - null
    tailf-ned-cisco-ios:login:
      on-success: {}
    tailf-ned-cisco-ios:cdp:
      run: true
    tailf-ned-cisco-ios:platform:
      console: serial
      punt-keepalive:
        disable-kernel-core: true
      qfp:
        utilization:
          monitor:
            load: 80
    tailf-ned-cisco-ios:call-home:
      contact-email-addr: sch-smart-licensing@cisco.com
      profile:
      - name: CiscoTAC-1
        active: true
        reporting:
          smart-licensing-data: true
        destination:
          transport-method:
            http:
            - null
    tailf-ned-cisco-ios:ip:
      gratuitous-arps-conf: {}
      bootp:
        server: true
      domain:
        lookup-conf:
          lookup: true
      name-server: {}
      ssh:
        server:
          algorithm: {}
        client:
          algorithm:
            encryption:
            - aes128-ctr
            - aes192-ctr
            - aes256-ctr
      forward-protocol:
        nd:
        - null
      http: {}
      bgp-community:
        new-format:
        - null
      extcommunity-list:
        standard: {}
      prefix-list: {}
    tailf-ned-cisco-ios:subscriber:
      templating: true
    tailf-ned-cisco-ios:multilink:
      bundle-name: authenticated
    tailf-ned-cisco-ios:username:
    - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      privilege: 15
      secret:
        type: '9'
        secret: $9$Kk15i.DS5I7ATE$G7j6P.Cn1LcVnpKh7eHcyGFc24V0mh/j1fd28jymgFc
    tailf-ned-cisco-ios:redundancy: {}
    tailf-ned-cisco-ios:crypto:
      pki:
        trustpoint:
        - id: SLA-TrustPoint
          enrollment:
            pkcs12:
            - null
          revocation-check:
          - crl
        - id: TP-self-signed-22217082
          enrollment:
            selfsigned:
            - null
          subject-name: cn=IOS-Self-Signed-Certificate-22217082
          revocation-check:
          - none
          rsakeypair:
            key-label: TP-self-signed-22217082
        certificate:
          chain:
          - name: SLA-TrustPoint
            certificate:
            - serial: '01'
              cert-type: ca
              cert: "  30820321 30820209 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 0B050030 \r\n  32310E30 0C060355 040A1305 43697363 6F312030 1E060355\
                \ 04031317 43697363 \r\n  6F204C69 63656E73 696E6720 526F6F74 20434130\
                \ 1E170D31 33303533 30313934 \r\n  3834375A 170D3338 30353330 31393438\
                \ 34375A30 32310E30 0C060355 040A1305 \r\n  43697363 6F312030 1E060355\
                \ 04031317 43697363 6F204C69 63656E73 696E6720 \r\n  526F6F74 20434130\
                \ 82012230 0D06092A 864886F7 0D010101 05000382 010F0030 \r\n  82010A02\
                \ 82010100 A6BCBD96 131E05F7 145EA72C 2CD686E6 17222EA1 F1EFF64D \r\
                \n  CBB4C798 212AA147 C655D8D7 9471380D 8711441E 1AAF071A 9CAE6388\
                \ 8A38E520 \r\n  1C394D78 462EF239 C659F715 B98C0A59 5BBB5CBD 0CFEBEA3\
                \ 700A8BF7 D8F256EE \r\n  4AA4E80D DB6FD1C9 60B1FD18 FFC69C96 6FA68957\
                \ A2617DE7 104FDC5F EA2956AC \r\n  7390A3EB 2B5436AD C847A2C5 DAB553EB\
                \ 69A9A535 58E9F3E3 C0BD23CF 58BD7188 \r\n  68E69491 20F320E7 948E71D7\
                \ AE3BCC84 F10684C7 4BC8E00F 539BA42B 42C68BB7 \r\n  C7479096 B4CB2D62\
                \ EA2F505D C7B062A4 6811D95B E8250FC4 5D5D5FB8 8F27D191 \r\n  C55F0D76\
                \ 61F9A4CD 3D992327 A8BB03BD 4E6D7069 7CBADF8B DF5F4368 95135E44 \r\
                \n  DFC7C6CF 04DD7FD1 02030100 01A34230 40300E06 03551D0F 0101FF04\
                \ 04030201 \r\n  06300F06 03551D13 0101FF04 05300301 01FF301D 0603551D\
                \ 0E041604 1449DC85 \r\n  4B3D31E5 1B3E6A17 606AF333 3D3B4C73 E8300D06\
                \ 092A8648 86F70D01 010B0500 \r\n  03820101 00507F24 D3932A66 86025D9F\
                \ E838AE5C 6D4DF6B0 49631C78 240DA905 \r\n  604EDCDE FF4FED2B 77FC460E\
                \ CD636FDB DD44681E 3A5673AB 9093D3B1 6C9E3D8B \r\n  D98987BF E40CBD9E\
                \ 1AECA0C2 2189BB5C 8FA85686 CD98B646 5575B146 8DFC66A8 \r\n  467A3DF4\
                \ 4D565700 6ADF0F0D CF835015 3C04FF7C 21E878AC 11BA9CD2 55A9232C \r\
                \n  7CA7B7E6 C1AF74F6 152E99B7 B1FCF9BB E973DE7F 5BDDEB86 C71E3B49\
                \ 1765308B \r\n  5FB0DA06 B92AFE7F 494E8A9E 07B85737 F3A58BE1 1A48A229\
                \ C37C1E69 39F08678 \r\n  80DDCD16 D6BACECA EEBC7CF9 8428787B 35202CDC\
                \ 60E4616A B623CDBD 230E3AFB \r\n  418616A9 4093E049 4D10AB75 27E86F73\
                \ 932E35B5 8862FDAE 0275156F 719BB2F0 \r\n  D697DF7F 28\r\n"
          - name: TP-self-signed-22217082
            certificate:
            - serial: '01'
              cert-type: self-signed
              cert: "  3082032C 30820214 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 05050030 \r\n  2F312D30 2B060355 04031324 494F532D 53656C66 2D536967\
                \ 6E65642D 43657274 \r\n  69666963 6174652D 32323231 37303832 301E170D\
                \ 32333035 31363136 32303336 \r\n  5A170D33 33303531 35313632 3033365A\
                \ 302F312D 302B0603 55040313 24494F53 \r\n  2D53656C 662D5369 676E6564\
                \ 2D436572 74696669 63617465 2D323232 31373038 \r\n  32308201 22300D06\
                \ 092A8648 86F70D01 01010500 0382010F 00308201 0A028201 \r\n  0100AACB\
                \ 8E1F5503 49CBF159 689C61A0 30611E12 7621B923 6ABE7FEA BCF6D9C6 \r\
                \n  1C2474A5 E1B17400 2709D64B 78D2F006 E7B02A5E DD596ACA 6002561A\
                \ FDDC83A0 \r\n  29A317AA 27AEF8EE 2B756E88 74599EBB B3A99D85 CFE21EAD\
                \ B752773C 4A11CFFE \r\n  329108CA BD8F6782 B833C0D9 3B6054B2 EEB072F3\
                \ 7B10855B 0441720E 0FFD3807 \r\n  2A46314A F561F1EA C6BDC01A 0B84E83F\
                \ 4B1FB8F3 31F49D82 4E637D29 FC701036 \r\n  0E2C7418 2EC79A86 54016525\
                \ 53C8691B 5C89CAA4 F1AE8434 689F8038 ED0B8711 \r\n  C9304F2B FB11CD99\
                \ 55C1013B 98E6DD36 3518D05C 20F79FAC 03C5A701 32F9234A \r\n  5D18778F\
                \ 07A48F76 5D13F014 B30DD56D CEFA53F5 05D3C344 8A1CEE66 D07D7937 \r\
                \n  1EC30203 010001A3 53305130 0F060355 1D130101 FF040530 030101FF\
                \ 301F0603 \r\n  551D2304 18301680 14AEABFA 98C0D3C9 0422FFC8 8BF3CC85\
                \ 8C9EC2FD 2F301D06 \r\n  03551D0E 04160414 AEABFA98 C0D3C904 22FFC88B\
                \ F3CC858C 9EC2FD2F 300D0609 \r\n  2A864886 F70D0101 05050003 82010100\
                \ 52295249 0AFE5DA4 035B0A82 3F160E6D \r\n  3D642034 A7F76741 19922ED8\
                \ D02B7758 AA046709 DFF3A6B5 46A642E2 25454EBE \r\n  75004E49 B7B83CBB\
                \ 427ABB56 6C3EE854 69DF7A61 8701258B BB8A3C41 D71D8705 \r\n  E93D9D63\
                \ BB0070F9 0884337F E79E2A80 A8E18FFB 1CDC6A5B C8A06FAE 249BDA50 \r\
                \n  ADB59F46 899E8796 53952E7A 77B862C5 FCB23D68 2774C7B3 BDD125FC\
                \ D0DDB907 \r\n  FB6CDFA9 51841ADE 44C25CAC 55BDBC9F 8F1995A2 A8F98D85\
                \ 66C1374E 586B4931 \r\n  AC9A3730 231A7E55 69D04D67 E34844BE D018430E\
                \ 7E2A930C C3AC47EA A9446AA6 \r\n  1C9FA6E4 03AA6711 7A6E1978 116EC3BA\
                \ 9080771F CE3EE7AA A678395E FC455749 \r\n  5693F0E7 5EEE4319 1B726746\
                \ C6C7A6AC\r\n"
    tailf-ned-cisco-ios:interface:
      Loopback:
      - name: '0'
        vrf:
          forwarding: internal_1
        ip:
          address: {}
      - name: '100'
        ip:
          address: {}
      GigabitEthernet:
      - name: '1'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        vrf:
          forwarding: Mgmt-intf
        ip:
          address:
            dhcp: {}
      - name: '2'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '3'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '3.10'
        vrf:
          forwarding: internal_1
        ip:
          address: {}
        vrrp: []
      - name: '4'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '5'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '6'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '7'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '8'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
    tailf-ned-cisco-ios:banner: {}
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
      - first: '0'
        stopbits: '1'
      vty:
      - first: 0
        last: 4
        login:
          local:
          - null
        transport:
          input:
          - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      monitor: {}
      facility: syslog
    tailf-ned-cisco-ios:ntp:
      server:
        peer-list:
        - name: 216.239.35.0
        - name: 216.239.35.4
    tailf-ned-cisco-ios:spanning-tree:
      extend:
        system-id:
        - null
    tailf-ned-cisco-ios:diagnostic:
      bootup:
        level: minimal
    tailf-ned-cisco-ios:mpls:
      ldp:
        router-id:
          interface: Loopback100
          force:
          - null
    tailf-ned-cisco-ios:router:
      bgp:
      - as-no: 65100
        address-family:
          ipv4:
          - af: unicast
            maximum-paths:
              ibgp:
                paths:
                  number-of-paths: 2
          with-vrf:
            ipv4:
            - af: unicast
              vrf:
              - name: internal_1
                redistribute:
                  ospf:
                  - id: 1
                    route-map: from_ospf
                distance:
                  bgp:
                    local: 200
          vpnv4:
          - af: unicast
      ospf:
      - id: 1
        vrf: internal_1
        redistribute:
          bgp:
            as-no: 65100
            route-map: to_ospf
        network:
        - ip: 172.16.0.2
          mask: 0.0.0.0
          area: 0
        - ip: 172.16.255.1
          mask: 0.0.0.0
          area: 0
      - id: 100
        network:
        - ip: 10.0.0.2
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.3.1
          mask: 0.0.0.0
          area: 0
        - ip: 10.255.255.11
          mask: 0.0.0.0
          area: 0
    tailf-ned-cisco-ios:memory:
      free:
        low-watermark:
          processor: 71489
