mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '17.3'
    tailf-ned-cisco-ios:service:
      conf: {}
      timestamps:
        debug:
          datetime: {}
        log:
          datetime: {}
      call-home:
      - null
    tailf-ned-cisco-ios:login:
      on-success: {}
    tailf-ned-cisco-ios:platform:
      console: serial
      punt-keepalive:
        disable-kernel-core: true
      qfp:
        utilization:
          monitor:
            load: 80
    tailf-ned-cisco-ios:vrf:
      definition:
      - name: Mgmt-intf
    tailf-ned-cisco-ios:clock:
      timezone: {}
    tailf-ned-cisco-ios:call-home:
      contact-email-addr: sch-smart-licensing@cisco.com
      profile:
      - name: CiscoTAC-1
        active: true
        reporting:
          smart-licensing-data: true
        destination:
          transport-method:
            http:
            - null
    tailf-ned-cisco-ios:ip:
      gratuitous-arps-conf: {}
      bootp:
        server: true
      domain:
        lookup-conf:
          lookup: true
      name-server: {}
      ssh:
        server:
          algorithm: {}
        client:
          algorithm:
            encryption:
            - aes128-ctr
            - aes192-ctr
            - aes256-ctr
      forward-protocol:
        nd:
        - null
      http: {}
    tailf-ned-cisco-ios:subscriber:
      templating: true
    tailf-ned-cisco-ios:multilink:
      bundle-name: authenticated
    tailf-ned-cisco-ios:username:
    - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      privilege: 15
      secret:
        type: '9'
        secret: $9$oBvSIHsjWW5yxU$9MQUFaZ5GDxmn5slGJhD9.2s5HK7JjFeGZGLL4THwL.
    tailf-ned-cisco-ios:redundancy: {}
    tailf-ned-cisco-ios:crypto:
      pki:
        trustpoint:
        - id: SLA-TrustPoint
          enrollment:
            pkcs12:
            - null
          revocation-check:
          - crl
        - id: TP-self-signed-1720086203
          enrollment:
            selfsigned:
            - null
          subject-name: cn=IOS-Self-Signed-Certificate-1720086203
          revocation-check:
          - none
          rsakeypair:
            key-label: TP-self-signed-1720086203
        certificate:
          chain:
          - name: SLA-TrustPoint
            certificate:
            - serial: '01'
              cert-type: ca
              cert: "  30820321 30820209 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 0B050030 \r\n  32310E30 0C060355 040A1305 43697363 6F312030 1E060355\
                \ 04031317 43697363 \r\n  6F204C69 63656E73 696E6720 526F6F74 20434130\
                \ 1E170D31 33303533 30313934 \r\n  3834375A 170D3338 30353330 31393438\
                \ 34375A30 32310E30 0C060355 040A1305 \r\n  43697363 6F312030 1E060355\
                \ 04031317 43697363 6F204C69 63656E73 696E6720 \r\n  526F6F74 20434130\
                \ 82012230 0D06092A 864886F7 0D010101 05000382 010F0030 \r\n  82010A02\
                \ 82010100 A6BCBD96 131E05F7 145EA72C 2CD686E6 17222EA1 F1EFF64D \r\
                \n  CBB4C798 212AA147 C655D8D7 9471380D 8711441E 1AAF071A 9CAE6388\
                \ 8A38E520 \r\n  1C394D78 462EF239 C659F715 B98C0A59 5BBB5CBD 0CFEBEA3\
                \ 700A8BF7 D8F256EE \r\n  4AA4E80D DB6FD1C9 60B1FD18 FFC69C96 6FA68957\
                \ A2617DE7 104FDC5F EA2956AC \r\n  7390A3EB 2B5436AD C847A2C5 DAB553EB\
                \ 69A9A535 58E9F3E3 C0BD23CF 58BD7188 \r\n  68E69491 20F320E7 948E71D7\
                \ AE3BCC84 F10684C7 4BC8E00F 539BA42B 42C68BB7 \r\n  C7479096 B4CB2D62\
                \ EA2F505D C7B062A4 6811D95B E8250FC4 5D5D5FB8 8F27D191 \r\n  C55F0D76\
                \ 61F9A4CD 3D992327 A8BB03BD 4E6D7069 7CBADF8B DF5F4368 95135E44 \r\
                \n  DFC7C6CF 04DD7FD1 02030100 01A34230 40300E06 03551D0F 0101FF04\
                \ 04030201 \r\n  06300F06 03551D13 0101FF04 05300301 01FF301D 0603551D\
                \ 0E041604 1449DC85 \r\n  4B3D31E5 1B3E6A17 606AF333 3D3B4C73 E8300D06\
                \ 092A8648 86F70D01 010B0500 \r\n  03820101 00507F24 D3932A66 86025D9F\
                \ E838AE5C 6D4DF6B0 49631C78 240DA905 \r\n  604EDCDE FF4FED2B 77FC460E\
                \ CD636FDB DD44681E 3A5673AB 9093D3B1 6C9E3D8B \r\n  D98987BF E40CBD9E\
                \ 1AECA0C2 2189BB5C 8FA85686 CD98B646 5575B146 8DFC66A8 \r\n  467A3DF4\
                \ 4D565700 6ADF0F0D CF835015 3C04FF7C 21E878AC 11BA9CD2 55A9232C \r\
                \n  7CA7B7E6 C1AF74F6 152E99B7 B1FCF9BB E973DE7F 5BDDEB86 C71E3B49\
                \ 1765308B \r\n  5FB0DA06 B92AFE7F 494E8A9E 07B85737 F3A58BE1 1A48A229\
                \ C37C1E69 39F08678 \r\n  80DDCD16 D6BACECA EEBC7CF9 8428787B 35202CDC\
                \ 60E4616A B623CDBD 230E3AFB \r\n  418616A9 4093E049 4D10AB75 27E86F73\
                \ 932E35B5 8862FDAE 0275156F 719BB2F0 \r\n  D697DF7F 28\r\n"
          - name: TP-self-signed-1720086203
            certificate:
            - serial: '01'
              cert-type: self-signed
              cert: "  30820330 30820218 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 05050030 \r\n  31312F30 2D060355 04031326 494F532D 53656C66 2D536967\
                \ 6E65642D 43657274 \r\n  69666963 6174652D 31373230 30383632 3033301E\
                \ 170D3233 30333133 32333037 \r\n  35355A17 0D333330 33313232 33303735\
                \ 355A3031 312F302D 06035504 03132649 \r\n  4F532D53 656C662D 5369676E\
                \ 65642D43 65727469 66696361 74652D31 37323030 \r\n  38363230 33308201\
                \ 22300D06 092A8648 86F70D01 01010500 0382010F 00308201 \r\n  0A028201\
                \ 01009198 D989BCB4 4C1EBE17 C9877DC6 EA53FB0C 23D49C00 9FB6E657 \r\
                \n  F28FD71A E4CFD485 22A79DBE 021089B5 F427B7B3 EA29EFE2 417962BC\
                \ C5F2142F \r\n  800D82A0 3E35FEC3 294A8439 A89CFFE1 3D9E1B09 A9747A58\
                \ 4FA0F168 C7A15DC2 \r\n  C7C3B464 D4685749 C0DAB90D 17833808 DFB8AA3C\
                \ 8932C1B9 5B89AC62 8613F9BD \r\n  A6608DC8 E239CABB 1DFA0B07 EFC507C9\
                \ 2F61DBB4 74E58D40 CA68294B B4AC8D2D \r\n  B6F95202 FCC2FB7F F57E2C0A\
                \ E93828D2 58668FFE 84E62350 0E186710 A9AE5411 \r\n  95EE6712 F37E5DA2\
                \ 328F964D 9D46C003 73D744E9 997EDEDA 7C0B7812 DC219080 \r\n  244D4CD4\
                \ F0C8D17E 249973AB 542CDC30 BFFDF372 08E35289 2C065ED9 380B88D1 \r\
                \n  046575D8 8FD10203 010001A3 53305130 0F060355 1D130101 FF040530\
                \ 030101FF \r\n  301F0603 551D2304 18301680 14C6B9EA 288E9CED 7E4F952A\
                \ B9889BE8 64FC2C8A \r\n  73301D06 03551D0E 04160414 C6B9EA28 8E9CED7E\
                \ 4F952AB9 889BE864 FC2C8A73 \r\n  300D0609 2A864886 F70D0101 05050003\
                \ 82010100 35E2FDA1 C82D4611 FB8F6B6F \r\n  EC8B4B38 79CA7297 C4703507\
                \ 4B869ACB 11155C3C 5402883F 88329AB2 8226A123 \r\n  8DBC3797 DB4E053C\
                \ 9A2A0032 BA31A9D6 DB4B51CB 4166E22B BC92C7A3 C33C809E \r\n  CA85F048\
                \ B9BE3E2A 24C6BFF2 96D5300F 7DD16B13 EAC5C9D7 70F18BA0 FB2C4E06 \r\
                \n  B2324273 C2727DF7 61029BCC 9F39413F 45842DE2 F1529206 B99C612F\
                \ 5BD39AB6 \r\n  5C539A0A EA0CEB1B 00A8FA6D 15AD1922 43E50694 4E2F9017\
                \ B975ACA0 2D85837B \r\n  1A2E4D5E B0221B61 90D54226 73BDD117 5FC0F8E8\
                \ 2E4DBB1A 2D15846B EDBFB785 \r\n  59AF26A7 D910D14C 04B31A22 02BB6117\
                \ B9C416DC BCAA921B F89E6F10 E9E05831 \r\n  7FF12951 CA724C04 3B51E3B6\
                \ 75FAE664 4C50FB69\r\n"
    tailf-ned-cisco-ios:interface:
      Loopback:
      - name: '0'
        ip:
          address: {}
      GigabitEthernet:
      - name: '1'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        vrf:
          forwarding: Mgmt-intf
        ip:
          address:
            dhcp: {}
      - name: '2'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          address: {}
      - name: '3'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          address: {}
      - name: '4'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          address: {}
      - name: '5'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          address: {}
      - name: '6'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '7'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '8'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
    tailf-ned-cisco-ios:banner: {}
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
      - first: '0'
        stopbits: '1'
      vty:
      - first: 0
        last: 4
        login:
          local:
          - null
        transport:
          input:
          - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      monitor: {}
      facility: syslog
    tailf-ned-cisco-ios:spanning-tree:
      extend:
        system-id:
        - null
    tailf-ned-cisco-ios:diagnostic:
      bootup:
        level: minimal
    tailf-ned-cisco-ios:mpls:
      ip: true
      mpls-ip-conf:
        ip:
          propagate-ttl-conf:
            propagate-ttl: true
      ldp:
        discovery:
          hello:
            holdtime: 15
            interval: 5
        router-id:
          interface: Loopback0
    tailf-ned-cisco-ios:router:
      ospf:
      - network:
        - ip: 10.0.0.1
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.5
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.9
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.13
          mask: 0.0.0.0
          area: 0
        - ip: 10.255.255.1
          mask: 0.0.0.0
          area: 0
    tailf-ned-cisco-ios:memory:
      free:
        low-watermark:
          processor: 71489
