---
mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '17.3'
    tailf-ned-cisco-ios:service:
      conf: {}
      timestamps: {}
      call-home:
      - null
    tailf-ned-cisco-ios:login:
      on-success: {}
    tailf-ned-cisco-ios:cdp:
      run: true
    tailf-ned-cisco-ios:platform:
      console: serial
      punt-keepalive:
        disable-kernel-core: true
      qfp:
        utilization:
          monitor:
            load: 80
    tailf-ned-cisco-ios:call-home:
      contact-email-addr: sch-smart-licensing@cisco.com
      profile:
      - name: CiscoTAC-1
        active: true
        reporting:
          smart-licensing-data: true
        destination:
          transport-method:
            http:
            - null
    tailf-ned-cisco-ios:ip:
      gratuitous-arps-conf: {}
      bootp:
        server: true
      domain:
        lookup-conf:
          lookup: true
      name-server: {}
      ssh:
        server:
          algorithm: {}
        client:
          algorithm:
            encryption:
            - aes128-ctr
            - aes192-ctr
            - aes256-ctr
      forward-protocol:
        nd:
        - null
      http: {}
      bgp-community:
        new-format:
        - null
    tailf-ned-cisco-ios:subscriber:
      templating: true
    tailf-ned-cisco-ios:multilink:
      bundle-name: authenticated
    tailf-ned-cisco-ios:username:
    - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      privilege: 15
      secret:
        type: '9'
        secret: $9$5skJA8GRHNB24.$KKjODE6EIIUCKKGnbv.EdH00JQ0n9sAm1ixOEzsNTlQ
    tailf-ned-cisco-ios:redundancy: {}
    tailf-ned-cisco-ios:crypto:
      pki:
        trustpoint:
        - id: SLA-TrustPoint
          enrollment:
            pkcs12:
            - null
          revocation-check:
          - crl
        - id: TP-self-signed-1024850120
          enrollment:
            selfsigned:
            - null
          subject-name: cn=IOS-Self-Signed-Certificate-1024850120
          revocation-check:
          - none
          rsakeypair:
            key-label: TP-self-signed-1024850120
        certificate:
          chain:
          - name: SLA-TrustPoint
            certificate:
            - serial: '01'
              cert-type: ca
              cert: "  30820321 30820209 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 0B050030 \r\n  32310E30 0C060355 040A1305 43697363 6F312030 1E060355\
                \ 04031317 43697363 \r\n  6F204C69 63656E73 696E6720 526F6F74 20434130\
                \ 1E170D31 33303533 30313934 \r\n  3834375A 170D3338 30353330 31393438\
                \ 34375A30 32310E30 0C060355 040A1305 \r\n  43697363 6F312030 1E060355\
                \ 04031317 43697363 6F204C69 63656E73 696E6720 \r\n  526F6F74 20434130\
                \ 82012230 0D06092A 864886F7 0D010101 05000382 010F0030 \r\n  82010A02\
                \ 82010100 A6BCBD96 131E05F7 145EA72C 2CD686E6 17222EA1 F1EFF64D \r\
                \n  CBB4C798 212AA147 C655D8D7 9471380D 8711441E 1AAF071A 9CAE6388\
                \ 8A38E520 \r\n  1C394D78 462EF239 C659F715 B98C0A59 5BBB5CBD 0CFEBEA3\
                \ 700A8BF7 D8F256EE \r\n  4AA4E80D DB6FD1C9 60B1FD18 FFC69C96 6FA68957\
                \ A2617DE7 104FDC5F EA2956AC \r\n  7390A3EB 2B5436AD C847A2C5 DAB553EB\
                \ 69A9A535 58E9F3E3 C0BD23CF 58BD7188 \r\n  68E69491 20F320E7 948E71D7\
                \ AE3BCC84 F10684C7 4BC8E00F 539BA42B 42C68BB7 \r\n  C7479096 B4CB2D62\
                \ EA2F505D C7B062A4 6811D95B E8250FC4 5D5D5FB8 8F27D191 \r\n  C55F0D76\
                \ 61F9A4CD 3D992327 A8BB03BD 4E6D7069 7CBADF8B DF5F4368 95135E44 \r\
                \n  DFC7C6CF 04DD7FD1 02030100 01A34230 40300E06 03551D0F 0101FF04\
                \ 04030201 \r\n  06300F06 03551D13 0101FF04 05300301 01FF301D 0603551D\
                \ 0E041604 1449DC85 \r\n  4B3D31E5 1B3E6A17 606AF333 3D3B4C73 E8300D06\
                \ 092A8648 86F70D01 010B0500 \r\n  03820101 00507F24 D3932A66 86025D9F\
                \ E838AE5C 6D4DF6B0 49631C78 240DA905 \r\n  604EDCDE FF4FED2B 77FC460E\
                \ CD636FDB DD44681E 3A5673AB 9093D3B1 6C9E3D8B \r\n  D98987BF E40CBD9E\
                \ 1AECA0C2 2189BB5C 8FA85686 CD98B646 5575B146 8DFC66A8 \r\n  467A3DF4\
                \ 4D565700 6ADF0F0D CF835015 3C04FF7C 21E878AC 11BA9CD2 55A9232C \r\
                \n  7CA7B7E6 C1AF74F6 152E99B7 B1FCF9BB E973DE7F 5BDDEB86 C71E3B49\
                \ 1765308B \r\n  5FB0DA06 B92AFE7F 494E8A9E 07B85737 F3A58BE1 1A48A229\
                \ C37C1E69 39F08678 \r\n  80DDCD16 D6BACECA EEBC7CF9 8428787B 35202CDC\
                \ 60E4616A B623CDBD 230E3AFB \r\n  418616A9 4093E049 4D10AB75 27E86F73\
                \ 932E35B5 8862FDAE 0275156F 719BB2F0 \r\n  D697DF7F 28\r\n"
          - name: TP-self-signed-1024850120
            certificate:
            - serial: '01'
              cert-type: self-signed
              cert: "  30820330 30820218 A0030201 02020101 300D0609 2A864886 F70D0101\
                \ 05050030 \r\n  31312F30 2D060355 04031326 494F532D 53656C66 2D536967\
                \ 6E65642D 43657274 \r\n  69666963 6174652D 31303234 38353031 3230301E\
                \ 170D3233 30353136 31363230 \r\n  34355A17 0D333330 35313531 36323034\
                \ 355A3031 312F302D 06035504 03132649 \r\n  4F532D53 656C662D 5369676E\
                \ 65642D43 65727469 66696361 74652D31 30323438 \r\n  35303132 30308201\
                \ 22300D06 092A8648 86F70D01 01010500 0382010F 00308201 \r\n  0A028201\
                \ 0100C736 E20F5A18 898D92F0 EF8F5698 7770E86B 38B9247C 8964D59E \r\
                \n  3D69C2F6 DA8442EA 0059BB91 DAB90772 B1100A13 4EC42A4A 0414FC88\
                \ 4A493FA3 \r\n  C43058EF 24407351 A8A14925 1E0B5928 AB3AD5FF 2B0E497D\
                \ 1A7DEE05 2160CAA2 \r\n  8F1722D9 A24F44A8 AB52F9FC EE4F39D3 14C3FB28\
                \ ADCF24B0 2CC4A886 34D5FBDC \r\n  79EA49F7 B6F51DD7 5CABBA5C EC77B3F5\
                \ 57172E13 12E2D1FE B1174BCE 521146C5 \r\n  BCD96806 2F4A2021 A93D6CF9\
                \ 68A47643 19D26226 E7D986AF 90B46B85 1BFF3658 \r\n  8FB6962E 6CB094BF\
                \ A3D0A8F3 A08CF6EB AAE60DD2 4BBA208D A4B8884F 70856CFE \r\n  EAAD77E5\
                \ 905B98A6 810AF54B D76B48CB B4A5FFEE 3BE1EB51 A3DE794B 27AA5752 \r\
                \n  1636FD2B 80BD0203 010001A3 53305130 0F060355 1D130101 FF040530\
                \ 030101FF \r\n  301F0603 551D2304 18301680 14B8DF7F F53146DC 9B685493\
                \ 457A5874 5DDB938A \r\n  3A301D06 03551D0E 04160414 B8DF7FF5 3146DC9B\
                \ 68549345 7A58745D DB938A3A \r\n  300D0609 2A864886 F70D0101 05050003\
                \ 82010100 8DA84EF5 E31201C7 7FD4FD9D \r\n  60257F85 25205E93 FBD7B12E\
                \ 0E5A3FAC 906A696C B21A0865 6073B63D 6ACF2424 \r\n  71880675 2E8BC839\
                \ 164400D4 02B6D1A5 6C3A3D85 5AC78AD5 8210794C E66291F6 \r\n  961B41C9\
                \ B922A975 B943060E 4DB7C15C E4313AE9 38F168FD B0825837 9832EBC8 \r\
                \n  9AC48AD8 00CED541 38C56C8F 59296CEC 5C969325 BFE72B53 64E6B5F5\
                \ C4F0ADF1 \r\n  993D01E4 A2D6E7A9 AEAA79EE D744B9E1 0B032A45 B472DD28\
                \ C910DA6D ABEB4E71 \r\n  08F62D4E E9B91181 91BD041F 09D5280C C26D351B\
                \ AD722F2D E99AAD3E 34F81311 \r\n  2EC2CCB2 08E5C506 FC88199A 83058C3B\
                \ D4DBCDA8 F41723A8 4E0919DA 583CAFF5 \r\n  3DE57BAD EC240E73 337D3012\
                \ AA1EA2B7 ED12A3E5\r\n"
    tailf-ned-cisco-ios:interface:
      Loopback:
      - name: '0'
        ip:
          address: {}
      GigabitEthernet:
      - name: '1'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        vrf:
          forwarding: Mgmt-intf
        ip:
          address:
            dhcp: {}
      - name: '2'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '3'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '4'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '5'
        negotiation: {}
        cdp:
          enable: true
        mop:
          xenabled: false
          sysid: false
        mpls:
          ip:
          - null
        ip:
          address: {}
      - name: '6'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '7'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
      - name: '8'
        negotiation: {}
        mop:
          xenabled: false
          sysid: false
        ip:
          no-address:
            address: false
    tailf-ned-cisco-ios:banner: {}
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
      - first: '0'
        stopbits: '1'
      vty:
      - first: 0
        last: 4
        login:
          local:
          - null
        transport:
          input:
          - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      monitor: {}
      facility: syslog
    tailf-ned-cisco-ios:ntp:
      server:
        peer-list:
        - name: 216.239.35.0
        - name: 216.239.35.4
    tailf-ned-cisco-ios:spanning-tree:
      extend:
        system-id:
        - null
    tailf-ned-cisco-ios:diagnostic:
      bootup:
        level: minimal
    tailf-ned-cisco-ios:mpls:
      ldp:
        router-id:
          interface: Loopback0
          force:
          - null
    tailf-ned-cisco-ios:router:
      bgp:
      - as-no: 65100
        neighbor-tag:
          neighbor:
          - id: L3VPN_PEERS
            cluster-id: 10.255.255.1
        address-family:
          ipv4: []
          vpnv4:
          - af: unicast
      ospf:
      - id: 100
        network:
        - ip: 10.0.0.1
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.5
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.9
          mask: 0.0.0.0
          area: 0
        - ip: 10.0.0.13
          mask: 0.0.0.0
          area: 0
        - ip: 10.255.255.1
          mask: 0.0.0.0
          area: 0
    tailf-ned-cisco-ios:memory:
      free:
        low-watermark:
          processor: 71489
