---
mdd_data:
  config:
    tailf-ned-cisco-ios:tailfned:
      police: cirmode
    tailf-ned-cisco-ios:version: '15.2'
    tailf-ned-cisco-ios:service:
      conf:
        pad: true
      timestamps: {}
      compress-config:
      - null
    tailf-ned-cisco-ios:cdp:
      run: true
      advertise-v2: true
    tailf-ned-cisco-ios:ip:
      gratuitous-arps-conf: {}
      cef-conf:
        cef:
        - null
      bootp:
        server: true
      domain:
        lookup-conf:
          lookup: true
      name-server: {}
      ssh:
        server:
          algorithm: {}
        client:
          algorithm:
            encryption:
            - aes128-ctr
            - aes192-ctr
            - aes256-ctr
      forward-protocol:
        nd:
        - null
      http: {}
    tailf-ned-cisco-ios:username:
    - name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      privilege: 15
      secret:
        type: '5'
        secret: $1$izuL$sO3B7U.1tHRbKA/f7f44z.
    tailf-ned-cisco-ios:vtp:
      version: 1
      mode: server
    tailf-ned-cisco-ios:interface:
      Loopback:
      - name: '0'
        ip:
          address: {}
      GigabitEthernet:
      - name: 0/0
        negotiation: {}
        vrf:
          forwarding: Mgmt-intf
        ip:
          address:
            dhcp: {}
      - name: 0/1
        switchport:
          trunk:
            encapsulation: dot1q
        spanning-tree: {}
        negotiation: {}
      - name: 0/2
        switchport:
          trunk:
            encapsulation: dot1q
        spanning-tree: {}
        negotiation: {}
      - name: 0/3
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 1/0
        switchport: {}
        spanning-tree: {}
        negotiation: {}
      - name: 1/1
        switchport:
          trunk:
            encapsulation: dot1q
        spanning-tree: {}
        negotiation: {}
      - name: 1/2
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 1/3
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 2/0
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 2/1
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 2/2
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 2/3
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 3/0
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 3/1
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 3/2
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      - name: 3/3
        spanning-tree:
          guard: root
          link-type: point-to-point
        negotiation: {}
      Vlan:
      - name: 10
        ip:
          address: {}
    tailf-ned-cisco-ios:banner:
      exec: "\r\nIOSv - Cisco Systems Confidential -\r\n\r\nSupplemental End User\
        \ License Restrictions\r\n\r\nThis IOSv software is provided AS-IS without\
        \ warranty of any kind. Under no circumstances may this software be used separate\
        \ from the Cisco Modeling Labs Software that this software was provided with,\
        \ or deployed or used as part of a production environment.\r\n\r\nBy using\
        \ the software, you agree to abide by the terms and conditions of the Cisco\
        \ End User License Agreement at http://www.cisco.com/go/eula. Unauthorized\
        \ use or distribution of this software is expressly prohibited.\r\n"
      incoming: "\r\nIOSv - Cisco Systems Confidential -\r\n\r\nSupplemental End User\
        \ License Restrictions\r\n\r\nThis IOSv software is provided AS-IS without\
        \ warranty of any kind. Under no circumstances may this software be used separate\
        \ from the Cisco Modeling Labs Software that this software was provided with,\
        \ or deployed or used as part of a production environment.\r\n\r\nBy using\
        \ the software, you agree to abide by the terms and conditions of the Cisco\
        \ End User License Agreement at http://www.cisco.com/go/eula. Unauthorized\
        \ use or distribution of this software is expressly prohibited.\r\n"
    tailf-ned-cisco-ios:control-plane: {}
    tailf-ned-cisco-ios:line:
      console:
      - first: '0'
      aux:
      - first: '0'
      vty:
      - first: 0
        last: 4
        login:
          local:
          - null
        transport:
          input:
          - ssh
    tailf-ned-cisco-ios:logging:
      buffered: {}
      monitor: {}
      facility: syslog
    tailf-ned-cisco-ios:ntp:
      server:
        peer-list:
        - name: 216.239.35.0
        - name: 216.239.35.4
    tailf-ned-cisco-ios:spanning-tree:
      extend:
        system-id:
        - null
      portfast:
        edge:
          default:
          - null
      vlan: {}
